### ISSUE TITLE
Support for react native?

### ISSUE THREAD

**Issue by philolo1** [bugsnag/bugsnag-upload#6]
Hi do you plan to support react native in the near future. I would like to upload my sourcemap files to bugsnag so i can track the errors properly.

**Comment by Cawllec** [comment]
Hi @philolo1, we do currently support uploading source-maps, but not through this tool.  Checkout our [showing full stacktraces](https://docs.bugsnag.com/platforms/react-native/showing-full-stacktraces/) guide for more information on how to achieve this.
